// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg_Type int32

const (
	Msg_HIGH Msg_Type = 0
	Msg_NORM Msg_Type = 1
	Msg_LOW  Msg_Type = 2
)

var Msg_Type_name = map[int32]string{
	0: "HIGH",
	1: "NORM",
	2: "LOW",
}

var Msg_Type_value = map[string]int32{
	"HIGH": 0,
	"NORM": 1,
	"LOW":  2,
}

func (x Msg_Type) String() string {
	return proto.EnumName(Msg_Type_name, int32(x))
}

func (Msg_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0, 0}
}

type Msg struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Type                 Msg_Type `protobuf:"varint,3,opt,name=type,proto3,enum=model.Msg_Type" json:"type,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Msg) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Msg) GetType() Msg_Type {
	if m != nil {
		return m.Type
	}
	return Msg_HIGH
}

func (m *Msg) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func init() {
	proto.RegisterEnum("model.Msg_Type", Msg_Type_name, Msg_Type_value)
	proto.RegisterType((*Msg)(nil), "model.Msg")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbf, 0x49, 0x36, 0x9f, 0x76, 0x0e, 0x35, 0xcc, 0x41, 0x42, 0x8a, 0x12, 0xda, 0x4b,
	0x4e, 0xdb, 0x52, 0xc5, 0xa3, 0x17, 0x29, 0xb6, 0x60, 0x2c, 0x04, 0xd1, 0x73, 0x9a, 0x6c, 0x63,
	0x31, 0xe9, 0x2e, 0xc9, 0x06, 0xcd, 0x2f, 0xf0, 0xbf, 0xf8, 0x2b, 0x25, 0x1b, 0x44, 0x51, 0xe8,
	0xed, 0x61, 0x9e, 0x77, 0x66, 0x78, 0x71, 0x50, 0xd6, 0x39, 0x57, 0x95, 0xd4, 0x92, 0x9c, 0x52,
	0x66, 0xa2, 0xf0, 0x47, 0xb9, 0x94, 0x79, 0x21, 0xa6, 0x66, 0xb8, 0x69, 0xb6, 0x53, 0x51, 0x2a,
	0xdd, 0xf6, 0x19, 0xff, 0xfc, 0xb7, 0x7c, 0xad, 0x12, 0xa5, 0x44, 0x55, 0xf7, 0x7e, 0xfc, 0x0e,
	0x68, 0x47, 0x75, 0x4e, 0x43, 0xb4, 0x76, 0x99, 0x07, 0x01, 0x84, 0x4e, 0x6c, 0xed, 0x32, 0x22,
	0x64, 0x5a, 0xbc, 0x69, 0xcf, 0x0a, 0x20, 0x1c, 0xc4, 0x86, 0x69, 0x82, 0x4c, 0xb7, 0x4a, 0x78,
	0x76, 0x00, 0xe1, 0x70, 0x7e, 0xc2, 0xcd, 0x7b, 0x1e, 0xd5, 0x39, 0x7f, 0x68, 0x95, 0x88, 0x8d,
	0xec, 0x16, 0xb7, 0x95, 0x2c, 0x3d, 0xd6, 0x2f, 0x76, 0x3c, 0x9e, 0x20, 0xeb, 0x12, 0x74, 0x8c,
	0x6c, 0xb9, 0xba, 0x5d, 0xba, 0xff, 0x3a, 0xba, 0x5f, 0xc7, 0x91, 0x0b, 0x74, 0x84, 0xf6, 0xdd,
	0xfa, 0xc9, 0xb5, 0xe6, 0x1f, 0x80, 0x6c, 0x91, 0x3e, 0x4b, 0x3a, 0x43, 0xbb, 0x4e, 0x5a, 0xc2,
	0xef, 0xfb, 0xfe, 0x0f, 0xa6, 0x6b, 0x74, 0x52, 0xd9, 0xec, 0x35, 0x9d, 0xf2, 0xbe, 0x1b, 0xff,
	0xea, 0xc6, 0x17, 0x5d, 0x71, 0x7f, 0xf4, 0x67, 0xbe, 0xda, 0xeb, 0xab, 0xcb, 0xc7, 0xa4, 0x68,
	0xc4, 0x0c, 0xe8, 0x06, 0xed, 0x24, 0x7d, 0xa1, 0x43, 0xa9, 0x83, 0x27, 0x42, 0x98, 0xc1, 0xe6,
	0xbf, 0x11, 0x17, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x5f, 0x16, 0x11, 0x8e, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EchoClient interface {
	Say(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error)
	Count(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Echo_CountClient, error)
	Ack(ctx context.Context, opts ...grpc.CallOption) (Echo_AckClient, error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) Say(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error) {
	out := new(Msg)
	err := c.cc.Invoke(ctx, "/model.Echo/say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) Count(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Echo_CountClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Echo_serviceDesc.Streams[0], "/model.Echo/count", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoCountClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Echo_CountClient interface {
	Recv() (*wrappers.Int64Value, error)
	grpc.ClientStream
}

type echoCountClient struct {
	grpc.ClientStream
}

func (x *echoCountClient) Recv() (*wrappers.Int64Value, error) {
	m := new(wrappers.Int64Value)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *echoClient) Ack(ctx context.Context, opts ...grpc.CallOption) (Echo_AckClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Echo_serviceDesc.Streams[1], "/model.Echo/ack", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoAckClient{stream}
	return x, nil
}

type Echo_AckClient interface {
	Send(*wrappers.Int64Value) error
	Recv() (*wrappers.Int64Value, error)
	grpc.ClientStream
}

type echoAckClient struct {
	grpc.ClientStream
}

func (x *echoAckClient) Send(m *wrappers.Int64Value) error {
	return x.ClientStream.SendMsg(m)
}

func (x *echoAckClient) Recv() (*wrappers.Int64Value, error) {
	m := new(wrappers.Int64Value)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EchoServer is the server API for Echo service.
type EchoServer interface {
	Say(context.Context, *Msg) (*Msg, error)
	Count(*empty.Empty, Echo_CountServer) error
	Ack(Echo_AckServer) error
}

// UnimplementedEchoServer can be embedded to have forward compatible implementations.
type UnimplementedEchoServer struct {
}

func (*UnimplementedEchoServer) Say(ctx context.Context, req *Msg) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}
func (*UnimplementedEchoServer) Count(req *empty.Empty, srv Echo_CountServer) error {
	return status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (*UnimplementedEchoServer) Ack(srv Echo_AckServer) error {
	return status.Errorf(codes.Unimplemented, "method Ack not implemented")
}

func RegisterEchoServer(s *grpc.Server, srv EchoServer) {
	s.RegisterService(&_Echo_serviceDesc, srv)
}

func _Echo_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Echo/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Say(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_Count_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServer).Count(m, &echoCountServer{stream})
}

type Echo_CountServer interface {
	Send(*wrappers.Int64Value) error
	grpc.ServerStream
}

type echoCountServer struct {
	grpc.ServerStream
}

func (x *echoCountServer) Send(m *wrappers.Int64Value) error {
	return x.ServerStream.SendMsg(m)
}

func _Echo_Ack_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).Ack(&echoAckServer{stream})
}

type Echo_AckServer interface {
	Send(*wrappers.Int64Value) error
	Recv() (*wrappers.Int64Value, error)
	grpc.ServerStream
}

type echoAckServer struct {
	grpc.ServerStream
}

func (x *echoAckServer) Send(m *wrappers.Int64Value) error {
	return x.ServerStream.SendMsg(m)
}

func (x *echoAckServer) Recv() (*wrappers.Int64Value, error) {
	m := new(wrappers.Int64Value)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Echo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "say",
			Handler:    _Echo_Say_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "count",
			Handler:       _Echo_Count_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ack",
			Handler:       _Echo_Ack_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "msg.proto",
}
