apiVersion: v1
kind: Service
metadata:
  labels:
    run: svc
  name: svc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    run: svc    
  type: NodePort    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc
spec:
  replicas: 3
  selector:
    matchLabels:
      run: svc
  template:
    metadata:
      labels:
        run: svc
    spec:
      containers:
      - name: svc
        image: svc:1.0.0
        ports:
          - containerPort: 80
