apiVersion: v1
kind: Service
metadata:
    name: headless
spec:
    selector:
        app: headless
    type: ClusterIP
    clusterIP: None
    ports:
        - name: http
          port: 80
          protocol: TCP
