apiVersion: v1
kind: Service
metadata:
  name: echosvc
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8080'
spec:
  selector:
    app: echosvc
  ports:
  - name: grpc
    nodePort: 30100
    port: 8888
    targetPort: 8888
  type: NodePort
